### ISSUE TITLE
Request for Installation Instructions

### ISSUE THREAD

**Issue by GencoreOperative** [BTW-Community/Better-Terrain-Addon#1]
Hello,

This mod looks interesting and I am a big fan of terrain generation mods so would be keen to try it out at some point. When it is in a state where it is ready to be released could you provide some installation instructions for users on how to install this addon? I'm not sure but there appears to be a consensus around packaging the files up as a zip.

Thanks!

**Comment by ammoore00** [comment]
Yeah there'll be instructions for how to install (which is just the same method as BTW), just for now it is still in development.
