### ISSUE TITLE
Only one biome seems to generate

### ISSUE THREAD

**Issue by mortaljoe** [BTW-Community/Better-Terrain-Addon#2]
Unless I'm mistaken, only one biome is generating in the current version, maybe the wetlands. Is https://github.com/BTW-Community/Better-Terrain-Addon/blob/d114c84c26b9daac54505ebc4e95362766b81d84/src/minecraft/net/minecraft/src/BTABiomeConfiguration.java#L104 the cause?

**Comment by ammoore00** [comment]
Fixed now, new download link up on BTW forums.

Thanks!
