### ISSUE TITLE
Non deterministic generation when decorating biomes

### ISSUE THREAD

**Issue by sanedsf** [BTW-Community/Better-Terrain-Addon#25]
Mods installed: BTA, Deco, BWR-Revival, Craftguide
Seed: 17071991
BTA parameters: Ocean size 3
Coords: -357 64 -200

There should be a clay patch right behind the player, but there is not. It does not happen every time you create the map so in order to achieve this you need to test it many times.

![2021-10-11_21 07 17](https://user-images.githubusercontent.com/3881715/136835542-7875c114-a01d-45eb-8a40-f4f6e39522d7.png)

![2021-10-11_21 07 34](https://user-images.githubusercontent.com/3881715/136835558-d83bc3cd-5d73-426e-83d8-8c85f11cd8ce.png)

**Comment by ammoore00** [comment]
Unable to reproduce. Likely down to a difference between versions as when introducing slate generation I did not qualify a minimum version for it to generate (v2.0.1 was missing slate generation so worlds generated in 2.0.1 would be slightly different in terms of decorations than 2.0.2)

**Comment by ammoore00** [comment]
Finally figured it out. Bug was due to tree distributors being locked to the seed of the first world generated after launching the game. Fixed for next release.
