### ISSUE TITLE
Autumn leaves don't decay.

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/Better-Terrain-Addon#29]
#### Issue description
Autumn leaves don't decay after harvesting surrounding logs.

#### Steps to reproduce the issue

1.  Find autumn tree biome
2. Chop logs all the way up
3. Wait a minute or two

#### What's the expected result?

- leaves disappear and occasionally drop saplings

#### What's the actual result?

- leaves only disappear when manually broken

#### Additional details / screenshot

- [Screenshot](https://imgur.com/FxBEs4O)

**Comment by ammoore00** [comment]
Yeah it's a known issue. Deco leaves won't decay right away, but if you break one leaf manually the rest will decay.

Going to close this because it's an issue with Deco and not BTA, but yeah it is something I'm aware of and working on.

**Comment by AbbyRead** [comment]
Oh, okay cool.  Thanks for the heads up.
